TempSensor_NXP_Arduino: LM75B Class Reference
LM75B Class Reference
#include <TempSensor.h>
Public Types
enum reg_num { Temp , Conf , Thyst , Tos }
Public Types inherited from TempSensor
enum mode { COMPARATOR , INTERRUPT }
Public Member Functions
LM75B (const uint8_t i2c_address=(0x90 > > 1))
LM75B (TwoWire &wire, const uint8_t i2c_address=(0x90 > > 1))
virtual ~LM75B ()
virtual float temp (void) override
virtual void thresholds (const float v0, const float v1)
virtual void os_mode (const mode flag)
virtual float read (void)
bool ping (void)
int reg_w (const uint8_t reg_adr, uint8_t *data, const uint16_t size)
int reg_w (const uint8_t reg_adr, const uint8_t data)
int reg_r (const uint8_t reg_adr, uint8_t *data, const uint16_t size)
uint8_t reg_r (const uint8_t reg_adr)
void write_r8 (const uint8_t reg, const uint8_t val)
void write_r16 (const uint8_t reg, const uint16_t val)
uint8_t read_r8 (const uint8_t reg)
uint16_t read_r16 (const uint8_t reg)
void bit_op8 (const uint8_t reg, const uint8_t mask, const uint8_t value)
void bit_op16 (const uint8_t reg, const uint16_t mask, const uint16_t value)
Public Member Functions inherited from TempSensor
TempSensor (const uint8_t i2c_address)
TempSensor (TwoWire &wire, const uint8_t i2c_address)
virtual ~TempSensor ()
Detailed Description
LM75B class
About LM75B: https://www.nxp.com/products/sensors/i3c-ic-digital-temp-sensors/digital-temperature-sensor-and-thermal-watchdog:LM75B?_gl=1*kd25ib*_ga*NTA5NDE1NDA0LjE2NzgzNDYyNzA.*_ga_WM5LE0KMSH*MTY4MjEyMjc1OC42Mi4wLjE2ODIxMjI3NTguMC4wLjA.
Definition at line 59 of file TempSensor.h.
Member Enumeration Documentation
reg_num
enum LM75B::reg_num
Name of the PCT2075 registers
Enumerator
Temp
Temp register
Conf
Conf register
Thyst
Thyst register
Tos
Tos registe
Definition at line 63 of file TempSensor.h.
Constructor & Destructor Documentation
LM75B() [1/2]
LM75B::LM75B (const uint8_t i2c_address = (0x90 >> 1))
Create a PCT2075 instance connected to specified I2C pins with specified address
Parameters
i2c_address I2C-bus address (default: (0x90>>1))
Definition at line 24 of file TempSensor.cpp.
LM75B() [2/2]
LM75B::LM75B (TwoWire & wire, const uint8_t i2c_address = (0x90 >> 1))
Create a PCT2075 instance connected to specified I2C pins with specified address
Parameters
wire TwoWire instance
i2c_address I2C-bus address (default: (0x90>>1))
Definition at line 28 of file TempSensor.cpp.
~LM75B()
LM75B::~LM75B () virtual
Destructor of PCT2075
Definition at line 32 of file TempSensor.cpp.
Member Function Documentation
bit_op16()
void LM75B::bit_op16 (const uint8_t reg, const uint16_t mask, const uint16_t value)
bit_op8()
void LM75B::bit_op8 (const uint8_t reg, const uint8_t mask, const uint8_t value)
Register overwriting with bit-mask
Register can be updated by bit level
Parameters
reg register index/address/pointer
mask bit-mask to protect overwriting
value value to overwrite
Referenced by os_mode().
os_mode()
void LM75B::os_mode (const mode flag) virtual
Set OS operation mode
Parameters
flag use PCT2075::COMPARATOR or PCT2075::INTERRUPT values
Reimplemented in PCT2075, P3T1755, and P3T1085.
Definition at line 50 of file TempSensor.cpp.
ping()
bool LM75B::ping (void)
Ping the device
Returns
true when ACK
read()
virtual float LM75B::read (void) virtual
Get temperature value in degree Celsius [°C]
This method simply calls "temp()" method
Returns
temperature value in degree Celsius [°C]
Reimplemented from TempSensor.
Reimplemented in PCT2075, P3T1755, and P3T1085.
read_r16()
uint16_t LM75B::read_r16 (const uint8_t reg)
Register read, 16 bit
This 16 bit access may ot be common but it's useful for sensor devices
Parameters
reg register index/address/pointer
Returns
data value
Referenced by temp().
read_r8()
uint8_t LM75B::read_r8 (const uint8_t reg)
Register read, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
reg_r() [1/2]
uint8_t LM75B::reg_r (const uint8_t reg_adr)
Single register read
Parameters
reg register index/address/pointer
Returns
read data
reg_r() [2/2]
int LM75B::reg_r (const uint8_t reg_adr, uint8_t * data, const uint16_t size)
Multiple register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reg_w() [1/2]
int LM75B::reg_w (const uint8_t reg_adr, const uint8_t data)
Single register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reg_w() [2/2]
int LM75B::reg_w (const uint8_t reg_adr, uint8_t * data, const uint16_t size)
Multiple register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
temp()
float LM75B::temp (void) override virtual
Get temperature value in degree Celsius [°C]
Returns
temperature value in degree Celsius [°C]
Implements TempSensor.
Reimplemented in PCT2075, P3T1755, and P3T1085.
Definition at line 36 of file TempSensor.cpp.
thresholds()
void LM75B::thresholds (const float v0, const float v1) virtual
Set Overtemperature shutdown threshold (Tos) and hysteresis (Thyst) in degree Celsius [°C]
This method takes 2 values and higher value will set as the threshold (Tos) and another will be the hysteresis (Thyst)
Parameters
v0 a value in degree Celsius
v1 a value in degree Celsius
Reimplemented in PCT2075, P3T1085, and P3T1755.
Definition at line 41 of file TempSensor.cpp.
write_r16()
void LM75B::write_r16 (const uint8_t reg, const uint16_t val)
Register write, 16 bit
This 16 bit access may ot be common but it's useful for sensor devices
Parameters
reg register index/address/pointer
val data value
Referenced by thresholds().
write_r8()
void LM75B::write_r8 (const uint8_t reg, const uint8_t val)
Register write, 8 bit
Parameters
reg register index/address/pointer
val data value
The documentation for this class was generated from the following files:
TempSensor.h
TempSensor.cpp